

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"

volumes:
  db_data:
