

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pesquisa-2-app
    ports:
      - "9000:9000"
    networks:
      - laravel

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
